# Generated by Django 5.0.6 on 2024-05-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_datahandling_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Country name')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
            ],
            options={
                'verbose_name': 'manufacturer',
                'verbose_name_plural': 'manufacturers',
            },
        ),
        migrations.CreateModel(
            name='PrepMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Preparation method',
                'verbose_name_plural': 'Preparation methods',
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
            ],
            options={
                'verbose_name': 'product tag',
                'verbose_name_plural': 'product tags',
            },
        ),
        migrations.CreateModel(
            name='Taste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
            ],
            options={
                'verbose_name': 'Taste',
                'verbose_name_plural': 'Tastes',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Type',
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='title')),
                ('leaf', models.CharField(max_length=250, verbose_name='leaf')),
                ('composition', models.CharField(max_length=250, verbose_name='composition')),
                ('strength', models.CharField(choices=[('strong', 'strong'), ('medium', 'medium'), ('weak', 'weak')], max_length=120, verbose_name='strength')),
                ('description', models.TextField(verbose_name='Description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_country', to='tobacco.country', verbose_name='product_country')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_manufacturer', to='tobacco.manufacturer', verbose_name='manufacturer')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_photo', to='common.media', verbose_name='photo')),
                ('prep_method', models.ManyToManyField(blank=True, to='tobacco.prepmethod', verbose_name='tag')),
                ('tag', models.ManyToManyField(blank=True, to='tobacco.producttag', verbose_name='tag')),
                ('taste', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_taste', to='tobacco.taste', verbose_name='Product taste')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_type', to='tobacco.type', verbose_name='Product type')),
            ],
        ),
    ]
