# Generated by Django 5.0.6 on 2024-05-12 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataHandling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=120, verbose_name='Headline')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=120, verbose_name='Headline')),
                ('text', models.TextField(verbose_name='Text')),
            ],
        ),
        migrations.RemoveField(
            model_name='commonsettings',
            name='data_handling',
        ),
        migrations.RemoveField(
            model_name='commonsettings',
            name='policy',
        ),
    ]
