# Generated by Django 5.0.6 on 2024-05-13 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_datahandling_policy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lounge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('price', models.FloatField(verbose_name='Price')),
                ('rating_google', models.FloatField(verbose_name='Google rating')),
                ('rating_yandex', models.FloatField(verbose_name='Yandex rating')),
                ('working_hours', models.IntegerField(verbose_name='Working hours')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone number')),
                ('description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Metro name')),
                ('location', models.CharField(max_length=120, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='LoungeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_image', to='common.media', verbose_name='Second Image')),
                ('image3', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='third_image', to='common.media', verbose_name='Third Image')),
                ('image4', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fourth_image', to='common.media', verbose_name='Fourth Image')),
                ('lounge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lounge', to='lounge.lounge', verbose_name='Lounge')),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='common.media', verbose_name='Main Image')),
            ],
        ),
        migrations.AddField(
            model_name='lounge',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lounge.metro', verbose_name='Location, metro'),
        ),
    ]
