# Generated by Django 5.0.6 on 2024-05-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lounge', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lounge',
            options={'verbose_name': 'Lounge', 'verbose_name_plural': 'Lounges'},
        ),
        migrations.AlterModelOptions(
            name='loungeimage',
            options={'verbose_name': 'Lounge image', 'verbose_name_plural': 'Lounge images'},
        ),
        migrations.AlterModelOptions(
            name='metro',
            options={'verbose_name': 'Metro', 'verbose_name_plural': 'Metros'},
        ),
        migrations.AlterField(
            model_name='lounge',
            name='working_hours',
            field=models.CharField(max_length=120, verbose_name='Working hours'),
        ),
    ]
