# Generated by Django 5.0.6 on 2024-05-13 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_datahandling_policy_and_more'),
        ('tobacco', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='MixTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
            ],
            options={
                'verbose_name': 'Mix tag',
                'verbose_name_plural': 'Mix tags',
            },
        ),
        migrations.CreateModel(
            name='MixComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Title')),
                ('percentage', models.PositiveSmallIntegerField(verbose_name='Percentage')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_component', to='common.media', verbose_name='Image of component')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_component', to='tobacco.product', verbose_name='Product component')),
            ],
            options={
                'verbose_name': 'Component of a mix',
                'verbose_name_plural': 'Components of a mix',
            },
        ),
        migrations.CreateModel(
            name='Mix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('strength', models.IntegerField(verbose_name='Strength')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_title', to='mix.category', verbose_name='Category')),
                ('components', models.ManyToManyField(to='mix.mixcomponent', verbose_name='Components')),
                ('tag', models.ManyToManyField(blank=True, to='mix.mixtag', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Mix',
                'verbose_name_plural': 'Mixes',
            },
        ),
    ]
